<?php

/**
 * @file
 * PHPStan stubs for CiviCRM Api4 entity classes.
 *
 * These classes are dynamically generated by CiviCRM at runtime
 * and are not available as physical files for static analysis.
 * This stub provides type information so PHPStan can analyse
 * code that uses them without requiring baseline ignores.
 */

namespace Civi\Api4 {

  use Civi\Api4\Generic\DAOGetAction;
  use Civi\Api4\Generic\DAOCreateAction;
  use Civi\Api4\Generic\DAOUpdateAction;
  use Civi\Api4\Generic\DAODeleteAction;

  /**
   * @method static DAOGetAction get(bool $checkPermissions = TRUE)
   * @method static DAOCreateAction create(bool $checkPermissions = TRUE)
   * @method static DAOUpdateAction update(bool $checkPermissions = TRUE)
   * @method static DAODeleteAction delete(bool $checkPermissions = TRUE)
   */
  class Contribution {

  }

  /**
   * @method static DAOGetAction get(bool $checkPermissions = TRUE)
   * @method static DAOCreateAction create(bool $checkPermissions = TRUE)
   * @method static DAOUpdateAction update(bool $checkPermissions = TRUE)
   * @method static DAODeleteAction delete(bool $checkPermissions = TRUE)
   */
  class ContributionRecur {

  }

  /**
   * @method static DAOGetAction get(bool $checkPermissions = TRUE)
   * @method static DAOCreateAction create(bool $checkPermissions = TRUE)
   * @method static DAOUpdateAction update(bool $checkPermissions = TRUE)
   * @method static DAODeleteAction delete(bool $checkPermissions = TRUE)
   */
  class ContributionPage {

  }

  /**
   * @method static DAOGetAction get(bool $checkPermissions = TRUE)
   * @method static DAOCreateAction create(bool $checkPermissions = TRUE)
   * @method static DAOUpdateAction update(bool $checkPermissions = TRUE)
   * @method static DAODeleteAction delete(bool $checkPermissions = TRUE)
   */
  class Contact {

  }

  /**
   * @method static DAOGetAction get(bool $checkPermissions = TRUE)
   * @method static DAOCreateAction create(bool $checkPermissions = TRUE)
   * @method static DAOUpdateAction update(bool $checkPermissions = TRUE)
   * @method static DAODeleteAction delete(bool $checkPermissions = TRUE)
   */
  class PaymentProcessor {

  }

  /**
   * @method static DAOGetAction get(bool $checkPermissions = TRUE)
   * @method static DAOCreateAction create(bool $checkPermissions = TRUE)
   * @method static DAOUpdateAction update(bool $checkPermissions = TRUE)
   * @method static DAODeleteAction delete(bool $checkPermissions = TRUE)
   */
  class Membership {

  }

  /**
   * @method static DAOGetAction get(bool $checkPermissions = TRUE)
   * @method static DAOCreateAction create(bool $checkPermissions = TRUE)
   * @method static DAOUpdateAction update(bool $checkPermissions = TRUE)
   * @method static DAODeleteAction delete(bool $checkPermissions = TRUE)
   */
  class MembershipType {

  }


}
