<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from io.compuco.paymentprocessingcore/xml/schema/CRM/Paymentprocessingcore/PaymentAttempt.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:30bef5f72e36f1d8902fa14d1daa82f1)
 */
use CRM_Paymentprocessingcore_ExtensionUtil as E;

/**
 * Database access object for the PaymentAttempt entity.
 */
class CRM_Paymentprocessingcore_DAO_PaymentAttempt extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_payment_attempt';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contribution
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contribution_id;

  /**
   * FK to Contact (donor)
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * FK to Payment Processor
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_processor_id;

  /**
   * Processor type: 'stripe', 'gocardless', 'itas', etc.
   *
   * @var string
   *   (SQL type: varchar(50))
   *   Note that values will be retrieved from the database as a string.
   */
  public $processor_type;

  /**
   * Processor session ID (cs_... for Stripe, mandate_... for GoCardless)
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $processor_session_id;

  /**
   * Processor payment ID (pi_... for Stripe, payment_... for GoCardless)
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $processor_payment_id;

  /**
   * Attempt status: pending, completed, failed, cancelled
   *
   * @var string
   *   (SQL type: varchar(25))
   *   Note that values will be retrieved from the database as a string.
   */
  public $status;

  /**
   * When attempt was created
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * Last updated
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $updated_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_payment_attempt';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Payment Attempts') : E::ts('Payment Attempt');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.id',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contribution ID'),
          'description' => E::ts('FK to Contribution'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.contribution_id',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contribution"),
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact (donor)'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.contact_id',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contact"),
          ],
          'add' => NULL,
        ],
        'payment_processor_id' => [
          'name' => 'payment_processor_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Payment Processor ID'),
          'description' => E::ts('FK to Payment Processor'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.payment_processor_id',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'FKClassName' => 'CRM_Financial_DAO_PaymentProcessor',
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Payment Processor"),
          ],
          'add' => NULL,
        ],
        'processor_type' => [
          'name' => 'processor_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Processor Type'),
          'description' => E::ts('Processor type: \'stripe\', \'gocardless\', \'itas\', etc.'),
          'required' => TRUE,
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.processor_type',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Processor Type"),
          ],
          'add' => NULL,
        ],
        'processor_session_id' => [
          'name' => 'processor_session_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Processor Session ID'),
          'description' => E::ts('Processor session ID (cs_... for Stripe, mandate_... for GoCardless)'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.processor_session_id',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Processor Session ID"),
          ],
          'add' => NULL,
        ],
        'processor_payment_id' => [
          'name' => 'processor_payment_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Processor Payment ID'),
          'description' => E::ts('Processor payment ID (pi_... for Stripe, payment_... for GoCardless)'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.processor_payment_id',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Processor Payment ID"),
          ],
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Status'),
          'description' => E::ts('Attempt status: pending, completed, failed, cancelled'),
          'required' => TRUE,
          'maxlength' => 25,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.status',
          'default' => 'pending',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Status"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Paymentprocessingcore_BAO_PaymentAttempt::getStatuses',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'description' => E::ts('When attempt was created'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'label' => E::ts("Created Date"),
          ],
          'add' => NULL,
        ],
        'updated_date' => [
          'name' => 'updated_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Updated Date'),
          'description' => E::ts('Last updated'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_attempt.updated_date',
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_payment_attempt',
          'entity' => 'PaymentAttempt',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'label' => E::ts("Updated Date"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'payment_attempt', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'payment_attempt', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_contribution_id' => [
        'name' => 'index_contribution_id',
        'field' => [
          0 => 'contribution_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_payment_attempt::1::contribution_id',
      ],
      'index_processor_type' => [
        'name' => 'index_processor_type',
        'field' => [
          0 => 'processor_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_attempt::0::processor_type',
      ],
      'index_processor_session' => [
        'name' => 'index_processor_session',
        'field' => [
          0 => 'processor_session_id',
          1 => 'processor_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_attempt::0::processor_session_id::processor_type',
      ],
      'index_processor_payment' => [
        'name' => 'index_processor_payment',
        'field' => [
          0 => 'processor_payment_id',
          1 => 'processor_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_attempt::0::processor_payment_id::processor_type',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
