<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from io.compuco.paymentprocessingcore/xml/schema/CRM/Paymentprocessingcore/PaymentProcessorCustomer.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:414ffcd9306883bd74ea6d71d042f23d)
 */
use CRM_Paymentprocessingcore_ExtensionUtil as E;

/**
 * Database access object for the PaymentProcessorCustomer entity.
 */
class CRM_Paymentprocessingcore_DAO_PaymentProcessorCustomer extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_payment_processor_customer';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Payment Processor
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_processor_id;

  /**
   * Customer ID from payment processor (e.g., cus_... for Stripe, cu_... for GoCardless)
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $processor_customer_id;

  /**
   * FK to Contact
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * When customer record was created
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * Last updated
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $updated_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_payment_processor_customer';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Payment Processor Customers') : E::ts('Payment Processor Customer');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_processor_customer.id',
          'table_name' => 'civicrm_payment_processor_customer',
          'entity' => 'PaymentProcessorCustomer',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentProcessorCustomer',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'payment_processor_id' => [
          'name' => 'payment_processor_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Payment Processor ID'),
          'description' => E::ts('FK to Payment Processor'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_processor_customer.payment_processor_id',
          'table_name' => 'civicrm_payment_processor_customer',
          'entity' => 'PaymentProcessorCustomer',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentProcessorCustomer',
          'localizable' => 0,
          'FKClassName' => 'CRM_Financial_DAO_PaymentProcessor',
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Payment Processor"),
          ],
          'add' => NULL,
        ],
        'processor_customer_id' => [
          'name' => 'processor_customer_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Processor Customer ID'),
          'description' => E::ts('Customer ID from payment processor (e.g., cus_... for Stripe, cu_... for GoCardless)'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_processor_customer.processor_customer_id',
          'table_name' => 'civicrm_payment_processor_customer',
          'entity' => 'PaymentProcessorCustomer',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentProcessorCustomer',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Processor Customer ID"),
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_processor_customer.contact_id',
          'table_name' => 'civicrm_payment_processor_customer',
          'entity' => 'PaymentProcessorCustomer',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentProcessorCustomer',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contact"),
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'description' => E::ts('When customer record was created'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_processor_customer.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_payment_processor_customer',
          'entity' => 'PaymentProcessorCustomer',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentProcessorCustomer',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'label' => E::ts("Created Date"),
          ],
          'add' => NULL,
        ],
        'updated_date' => [
          'name' => 'updated_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Updated Date'),
          'description' => E::ts('Last updated'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_processor_customer.updated_date',
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_payment_processor_customer',
          'entity' => 'PaymentProcessorCustomer',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentProcessorCustomer',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'label' => E::ts("Updated Date"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'payment_processor_customer', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'payment_processor_customer', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_payment_processor_id' => [
        'name' => 'index_payment_processor_id',
        'field' => [
          0 => 'payment_processor_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_processor_customer::0::payment_processor_id',
      ],
      'index_processor_customer_id' => [
        'name' => 'index_processor_customer_id',
        'field' => [
          0 => 'processor_customer_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_processor_customer::0::processor_customer_id',
      ],
      'index_contact_id' => [
        'name' => 'index_contact_id',
        'field' => [
          0 => 'contact_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_processor_customer::0::contact_id',
      ],
      'unique_contact_processor' => [
        'name' => 'unique_contact_processor',
        'field' => [
          0 => 'contact_id',
          1 => 'payment_processor_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_payment_processor_customer::1::contact_id::payment_processor_id',
      ],
      'unique_processor_customer' => [
        'name' => 'unique_processor_customer',
        'field' => [
          0 => 'payment_processor_id',
          1 => 'processor_customer_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_payment_processor_customer::1::payment_processor_id::processor_customer_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
