<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from io.compuco.paymentprocessingcore/xml/schema/CRM/Paymentprocessingcore/PaymentWebhook.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:b0ce6e7d497283805646571a6b7e434a)
 */
use CRM_Paymentprocessingcore_ExtensionUtil as E;

/**
 * Database access object for the PaymentWebhook entity.
 */
class CRM_Paymentprocessingcore_DAO_PaymentWebhook extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_payment_webhook';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Processor event ID (evt_... for Stripe, evt_... for GoCardless)
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_id;

  /**
   * Processor type: 'stripe', 'gocardless', 'itas', etc.
   *
   * @var string
   *   (SQL type: varchar(50))
   *   Note that values will be retrieved from the database as a string.
   */
  public $processor_type;

  /**
   * Event type (e.g. checkout.session.completed, payment_intent.succeeded)
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_type;

  /**
   * FK to Payment Attempt
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_attempt_id;

  /**
   * Processing status: new, processing, processed, error
   *
   * @var string
   *   (SQL type: varchar(25))
   *   Note that values will be retrieved from the database as a string.
   */
  public $status;

  /**
   * Processing result: applied, noop, ignored_out_of_order, error
   *
   * @var string|null
   *   (SQL type: varchar(50))
   *   Note that values will be retrieved from the database as a string.
   */
  public $result;

  /**
   * Error details if processing failed
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $error_log;

  /**
   * When event was processed
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $processed_at;

  /**
   * When webhook was received
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_payment_webhook';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Payment Webhooks') : E::ts('Payment Webhook');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.id',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Event ID'),
          'description' => E::ts('Processor event ID (evt_... for Stripe, evt_... for GoCardless)'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.event_id',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Event ID"),
          ],
          'add' => NULL,
        ],
        'processor_type' => [
          'name' => 'processor_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Processor Type'),
          'description' => E::ts('Processor type: \'stripe\', \'gocardless\', \'itas\', etc.'),
          'required' => TRUE,
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.processor_type',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Processor Type"),
          ],
          'add' => NULL,
        ],
        'event_type' => [
          'name' => 'event_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Event Type'),
          'description' => E::ts('Event type (e.g. checkout.session.completed, payment_intent.succeeded)'),
          'required' => TRUE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.event_type',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Event Type"),
          ],
          'add' => NULL,
        ],
        'payment_attempt_id' => [
          'name' => 'payment_attempt_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Payment Attempt ID'),
          'description' => E::ts('FK to Payment Attempt'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.payment_attempt_id',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'FKClassName' => 'CRM_Paymentprocessingcore_DAO_PaymentAttempt',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Payment Attempt"),
          ],
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Status'),
          'description' => E::ts('Processing status: new, processing, processed, error'),
          'required' => TRUE,
          'maxlength' => 25,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.status',
          'default' => 'new',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Status"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Paymentprocessingcore_BAO_PaymentWebhook::getStatuses',
          ],
          'add' => NULL,
        ],
        'result' => [
          'name' => 'result',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Result'),
          'description' => E::ts('Processing result: applied, noop, ignored_out_of_order, error'),
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.result',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Result"),
          ],
          'add' => NULL,
        ],
        'error_log' => [
          'name' => 'error_log',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Error Log'),
          'description' => E::ts('Error details if processing failed'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.error_log',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Error Log"),
          ],
          'add' => NULL,
        ],
        'processed_at' => [
          'name' => 'processed_at',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Processed At'),
          'description' => E::ts('When event was processed'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.processed_at',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'label' => E::ts("Processed At"),
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'description' => E::ts('When webhook was received'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_payment_webhook.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_payment_webhook',
          'entity' => 'PaymentWebhook',
          'bao' => 'CRM_Paymentprocessingcore_DAO_PaymentWebhook',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'label' => E::ts("Created Date"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'payment_webhook', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'payment_webhook', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_event_id' => [
        'name' => 'index_event_id',
        'field' => [
          0 => 'event_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_payment_webhook::1::event_id',
      ],
      'index_processor_type' => [
        'name' => 'index_processor_type',
        'field' => [
          0 => 'processor_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_webhook::0::processor_type',
      ],
      'index_event_type' => [
        'name' => 'index_event_type',
        'field' => [
          0 => 'event_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_payment_webhook::0::event_type',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
