-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from file:drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_payment_webhook`;
DROP TABLE IF EXISTS `civicrm_payment_processor_customer`;
DROP TABLE IF EXISTS `civicrm_payment_attempt`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_payment_attempt
-- *
-- * Tracks payment attempts across all processors (Stripe, GoCardless, ITAS, etc.)
-- *
-- *******************************************************/
CREATE TABLE `civicrm_payment_attempt` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `contribution_id` int unsigned NOT NULL COMMENT 'FK to Contribution',
  `contact_id` int unsigned NULL COMMENT 'FK to Contact (donor)',
  `payment_processor_id` int unsigned NULL COMMENT 'FK to Payment Processor',
  `processor_type` varchar(50) NOT NULL COMMENT 'Processor type: \'stripe\', \'gocardless\', \'itas\', etc.',
  `processor_session_id` varchar(255) COMMENT 'Processor session ID (cs_... for Stripe, mandate_... for GoCardless)',
  `processor_payment_id` varchar(255) COMMENT 'Processor payment ID (pi_... for Stripe, payment_... for GoCardless)',
  `status` varchar(25) NOT NULL DEFAULT 'pending' COMMENT 'Attempt status: pending, completed, failed, cancelled',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When attempt was created',
  `updated_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last updated',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_contribution_id`(contribution_id),
  INDEX `index_processor_type`(processor_type),
  INDEX `index_processor_session`(processor_session_id, processor_type),
  INDEX `index_processor_payment`(processor_payment_id, processor_type),
  CONSTRAINT FK_civicrm_payment_attempt_contribution_id FOREIGN KEY (`contribution_id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_payment_attempt_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_payment_attempt_payment_processor_id FOREIGN KEY (`payment_processor_id`) REFERENCES `civicrm_payment_processor`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_payment_processor_customer
-- *
-- * Stores payment processor customer IDs for all processors (Stripe, GoCardless, ITAS, etc.)
-- *
-- *******************************************************/
CREATE TABLE `civicrm_payment_processor_customer` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `payment_processor_id` int unsigned NOT NULL COMMENT 'FK to Payment Processor',
  `processor_customer_id` varchar(255) NOT NULL COMMENT 'Customer ID from payment processor (e.g., cus_... for Stripe, cu_... for GoCardless)',
  `contact_id` int unsigned NOT NULL COMMENT 'FK to Contact',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When customer record was created',
  `updated_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last updated',
  PRIMARY KEY (`id`),
  INDEX `index_payment_processor_id`(payment_processor_id),
  INDEX `index_processor_customer_id`(processor_customer_id),
  INDEX `index_contact_id`(contact_id),
  UNIQUE INDEX `unique_contact_processor`(contact_id, payment_processor_id),
  UNIQUE INDEX `unique_processor_customer`(payment_processor_id, processor_customer_id),
  CONSTRAINT FK_civicrm_payment_processor_customer_payment_processor_id FOREIGN KEY (`payment_processor_id`) REFERENCES `civicrm_payment_processor`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_payment_processor_customer_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_payment_webhook
-- *
-- * Webhook event log for de-duplication and idempotency across all processors
-- *
-- *******************************************************/
CREATE TABLE `civicrm_payment_webhook` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `event_id` varchar(255) NOT NULL COMMENT 'Processor event ID (evt_... for Stripe, evt_... for GoCardless)',
  `processor_type` varchar(50) NOT NULL COMMENT 'Processor type: \'stripe\', \'gocardless\', \'itas\', etc.',
  `event_type` varchar(100) NOT NULL COMMENT 'Event type (e.g. checkout.session.completed, payment_intent.succeeded)',
  `payment_attempt_id` int unsigned NULL COMMENT 'FK to Payment Attempt',
  `status` varchar(25) NOT NULL DEFAULT 'new' COMMENT 'Processing status: new, processing, processed, error, permanent_error',
  `attempts` int unsigned NOT NULL DEFAULT 0 COMMENT 'Number of processing attempts',
  `next_retry_at` timestamp COMMENT 'When to retry processing (for exponential backoff)',
  `result` varchar(50) COMMENT 'Processing result: applied, noop, ignored_out_of_order, error',
  `error_log` text COMMENT 'Error details if processing failed',
  `processed_at` timestamp COMMENT 'When event was processed',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When webhook was received',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_event_processor`(event_id, processor_type),
  INDEX `index_event_type`(event_type),
  INDEX `index_status_retry`(status, next_retry_at),
  CONSTRAINT FK_civicrm_payment_webhook_payment_attempt_id FOREIGN KEY (`payment_attempt_id`) REFERENCES `civicrm_payment_attempt`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;
